final List<Map<String, dynamic>> seedShoes = [
  {
    'id': 1,
    'name': 'Air Max Retro',
    'brand': 'Nike',
    'price': 149.99,
    'category': 'Sneakers',
    'description': 'Classic retro design with modern comfort. Features responsive cushioning and a breathable upper for all-day wear.',
    'sizes': '7,8,9,10,11',
    'colors': 'Black,White,Red',
    'images': 'assets/images/shoes/shoe1.png,assets/images/shoes/shoe1_alt.png',
    'is_featured': 1,
    'is_new_arrival': 0,
  },
  {
    'id': 2,
    'name': 'UltraBoost Lite',
    'brand': 'Adidas',
    'price': 180.00,
    'category': 'Running',
    'description': 'Lightweight running shoes built for speed and endurance. The boost midsole returns energy with every step.',
    'sizes': '7,8,9,10',
    'colors': 'White,Blue,Grey',
    'images': 'assets/images/shoes/shoe2.png,assets/images/shoes/shoe2_alt.png',
    'is_featured': 1,
    'is_new_arrival': 1,
  },
  {
    'id': 3,
    'name': 'Classic Canvas',
    'brand': 'Converse',
    'price': 65.00,
    'category': 'Casual',
    'description': 'The iconic canvas sneaker that goes with everything. A timeless staple for your wardrobe.',
    'sizes': '8,9,10,11,12',
    'colors': 'Black,White,Navy',
    'images': 'assets/images/shoes/shoe3.png,assets/images/shoes/shoe3_alt.png',
    'is_featured': 0,
    'is_new_arrival': 0,
  },
  {
    'id': 4,
    'name': 'Gel-Nimbus 25',
    'brand': 'ASICS',
    'price': 160.00,
    'category': 'Running',
    'description': 'Maximum cushioning for long-distance runs. Experience the softest landing yet.',
    'sizes': '8,9,9.5,10,11',
    'colors': 'Blue,Black,Green',
    'images': 'assets/images/shoes/shoe4.png,assets/images/shoes/shoe4_alt.png',
    'is_featured': 0,
    'is_new_arrival': 1,
  },
  {
    'id': 5,
    'name': 'Jordan High OG',
    'brand': 'Nike',
    'price': 220.00,
    'category': 'Sneakers',
    'description': 'The classic high-top that started it all. Premium leather and responsive air cushioning.',
    'sizes': '9,10,11,12',
    'colors': 'Red,Black,White',
    'images': 'assets/images/shoes/shoe5.png,assets/images/shoes/shoe5_alt.png',
    'is_featured': 1,
    'is_new_arrival': 0,
  },
    {
    'id': 6,
    'name': 'React Infinity',
    'brand': 'Nike',
    'price': 165.00,
    'category': 'Running',
    'description': 'Designed to reduce injury and keep you running. More foam, improved upper.',
    'sizes': '7,8,9,10',
    'colors': 'Black,Grey,Orange',
    'images': 'assets/images/shoes/shoe6.png,assets/images/shoes/shoe6_alt.png',
    'is_featured': 0,
    'is_new_arrival': 0,
  },
  {
    'id': 7,
    'name': 'Club C 85',
    'brand': 'Reebok',
    'price': 85.00,
    'category': 'Casual',
    'description': 'Vintage style for the modern era. Soft leather upper for support and comfort.',
    'sizes': '7,8,9,10,11',
    'colors': 'White,Green,Black',
    'images': 'assets/images/shoes/shoe7.png,assets/images/shoes/shoe7_alt.png',
    'is_featured': 0,
    'is_new_arrival': 0,
  },
  {
    'id': 8,
    'name': 'ZoomX Vaporfly',
    'brand': 'Nike',
    'price': 250.00,
    'category': 'Running',
    'description': 'The next step in racing shoes. Built for record-breaking speed with unparalleled energy return.',
    'sizes': '8,9,10',
    'colors': 'Pink,Green,White',
    'images': 'assets/images/shoes/shoe8.png,assets/images/shoes/shoe8_alt.png',
    'is_featured': 1,
    'is_new_arrival': 1,
  },
  {
    'id': 9,
    'name': '574 Core',
    'brand': 'New Balance',
    'price': 90.00,
    'category': 'Casual',
    'description': 'The definitive New Balance sneaker. Combining classic styling with modern comfort.',
    'sizes': '7,8,9,10,11,12',
    'colors': 'Grey,Navy,Black',
    'images': 'assets/images/shoes/shoe9.png,assets/images/shoes/shoe9_alt.png',
    'is_featured': 0,
    'is_new_arrival': 0,
  },
  {
    'id': 10,
    'name': 'Curry Flow 10',
    'brand': 'Under Armour',
    'price': 160.00,
    'category': 'Sport',
    'description': 'Lighter, grippier, and bouncier basketball shoes designed for maximum court feel.',
    'sizes': '8,9,10,11',
    'colors': 'Blue,Yellow,White',
    'images': 'assets/images/shoes/shoe10.png,assets/images/shoes/shoe10_alt.png',
    'is_featured': 1,
    'is_new_arrival': 1,
  }
];
