final List<Map<String, dynamic>> seedShoes = [
  {
    'id': 1,
    'name': 'Air Max Retro',
    'brand': 'Nike',
    'price': 149.99,
    'category': 'Sneakers',
    'description': 'Classic retro design with modern comfort. Features responsive cushioning and a breathable upper for all-day wear.',
    'sizes': '7,8,9,10,11',
    'colors': 'Black,White,Red',
    'images': 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
    'is_featured': 1,
    'is_new_arrival': 0,
  },
  {
    'id': 2,
    'name': 'UltraBoost Lite',
    'brand': 'Adidas',
    'price': 180.00,
    'category': 'Running',
    'description': 'Lightweight running shoes built for speed and endurance. The boost midsole returns energy with every step.',
    'sizes': '7,8,9,10',
    'colors': 'White,Blue,Grey',
    'images': 'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?auto=format&fit=crop&w=800&q=80',
    'is_featured': 1,
    'is_new_arrival': 1,
  },
  {
    'id': 3,
    'name': 'Classic Canvas',
    'brand': 'Converse',
    'price': 65.00,
    'category': 'Casual',
    'description': 'The iconic canvas sneaker that goes with everything. A timeless staple for your wardrobe.',
    'sizes': '8,9,10,11,12',
    'colors': 'Black,White,Navy',
    'images': 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=800&q=80',
    'is_featured': 0,
    'is_new_arrival': 0,
  },
  {
    'id': 4,
    'name': 'Gel-Nimbus 25',
    'brand': 'ASICS',
    'price': 160.00,
    'category': 'Running',
    'description': 'Maximum cushioning for long-distance runs. Experience the softest landing yet.',
    'sizes': '8,9,9.5,10,11',
    'colors': 'Blue,Black,Green',
    'images': 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=800&q=80',
    'is_featured': 0,
    'is_new_arrival': 1,
  },
  {
    'id': 5,
    'name': 'Jordan High OG',
    'brand': 'Nike',
    'price': 220.00,
    'category': 'Sneakers',
    'description': 'The classic high-top that started it all. Premium leather and responsive air cushioning.',
    'sizes': '9,10,11,12',
    'colors': 'Red,Black,White',
    'images': 'https://images.unsplash.com/photo-1597043530274-0466e33ca270?auto=format&fit=crop&w=800&q=80',
    'is_featured': 1,
    'is_new_arrival': 0,
  },
  {
    'id': 6,
    'name': 'React Infinity',
    'brand': 'Nike',
    'price': 165.00,
    'category': 'Running',
    'description': 'Designed to reduce injury and keep you running. More foam, improved upper.',
    'sizes': '7,8,9,10',
    'colors': 'Black,Grey,Orange',
    'images': 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=800&q=80',
    'is_featured': 0,
    'is_new_arrival': 0,
  },
  {
    'id': 7,
    'name': 'Club C 85',
    'brand': 'Reebok',
    'price': 85.00,
    'category': 'Casual',
    'description': 'Vintage style for the modern era. Soft leather upper for support and comfort.',
    'sizes': '7,8,9,10,11',
    'colors': 'White,Green,Black',
    'images': 'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=800&q=80',
    'is_featured': 0,
    'is_new_arrival': 0,
  },
  {
    'id': 8,
    'name': 'ZoomX Vaporfly',
    'brand': 'Nike',
    'price': 250.00,
    'category': 'Running',
    'description': 'The next step in racing shoes. Built for record-breaking speed with unparalleled energy return.',
    'sizes': '8,9,10',
    'colors': 'Pink,Green,White',
    'images': 'https://images.unsplash.com/photo-1512374382149-433a72b9a5a5?auto=format&fit=crop&w=800&q=80',
    'is_featured': 1,
    'is_new_arrival': 1,
  },
  {
    'id': 9,
    'name': '574 Core',
    'brand': 'New Balance',
    'price': 90.00,
    'category': 'Casual',
    'description': 'The definitive New Balance sneaker. Combining classic styling with modern comfort.',
    'sizes': '7,8,9,10,11,12',
    'colors': 'Grey,Navy,Black',
    'images': 'https://images.unsplash.com/photo-1531310197839-ccf54634509e?auto=format&fit=crop&w=800&q=80',
    'is_featured': 0,
    'is_new_arrival': 0,
  },
  {
    'id': 10,
    'name': 'Curry Flow 10',
    'brand': 'Under Armour',
    'price': 160.00,
    'category': 'Sport',
    'description': 'Lighter, grippier, and bouncier basketball shoes designed for maximum court feel.',
    'sizes': '8,9,10,11',
    'colors': 'Blue,Yellow,White',
    'images': 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    'is_featured': 1,
    'is_new_arrival': 1,
  },
  // Added 20 more demo shoes
  {
    'id': 11,
    'name': 'Legacy High',
    'brand': 'Nike',
    'price': 130.00,
    'category': 'Sneakers',
    'description': 'Inspired by basketball icons of the 80s.',
    'sizes': '8,9,10,11',
    'colors': 'Black,White',
    'images': 'https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=800&q=80',
    'is_featured': 0,
    'is_new_arrival': 1,
  },
  {
    'id': 12,
    'name': 'Sk8-Hi',
    'brand': 'Vans',
    'price': 75.00,
    'category': 'Casual',
    'description': 'The legendary high top lace-up sneaker.',
    'sizes': '7,8,9,10,11',
    'colors': 'Black,Navy',
    'images': 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=800&q=80',
    'is_featured': 1,
    'is_new_arrival': 0,
  },
  {
    'id': 13,
    'name': 'Gazelle',
    'brand': 'Adidas',
    'price': 90.00,
    'category': 'Casual',
    'description': 'A low-profile classic born on the indoor courts.',
    'sizes': '8,9,10',
    'colors': 'Navy,Burgundy,Black',
    'images': 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
    'is_featured': 0,
    'is_new_arrival': 0,
  },
  {
    'id': 14,
    'name': 'Fresh Foam 880',
    'brand': 'New Balance',
    'price': 140.00,
    'category': 'Running',
    'description': 'Reliable everyday performance runner.',
    'sizes': '8,9,10,11,12',
    'colors': 'Grey,Blue',
    'images': 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80',
    'is_featured': 0,
    'is_new_arrival': 0,
  },
  {
    'id': 15,
    'name': 'Kyrie 8',
    'brand': 'Nike',
    'price': 140.00,
    'category': 'Sport',
    'description': 'Kyrie Irvings latest signature basketball shoe.',
    'sizes': '9,10,11',
    'colors': 'Multi,Black,White',
    'images': 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&w=800&q=80',
    'is_featured': 0,
    'is_new_arrival': 1,
  },
  {
    'id': 16,
    'name': 'Superstar',
    'brand': 'Adidas',
    'price': 100.00,
    'category': 'Sneakers',
    'description': 'The iconic shell-toe sneaker.',
    'sizes': '6,7,8,9,10',
    'colors': 'White,Black',
    'images': 'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=800&q=80',
    'is_featured': 1,
    'is_new_arrival': 0,
  },
  {
    'id': 17,
    'name': 'HOVR Phantom 3',
    'brand': 'Under Armour',
    'price': 140.00,
    'category': 'Running',
    'description': 'Plush cushioning and high energy return.',
    'sizes': '8,9,10,11',
    'colors': 'Red,Black',
    'images': 'https://images.unsplash.com/photo-1605348532760-6753d2c41329?auto=format&fit=crop&w=800&q=80',
    'is_featured': 0,
    'is_new_arrival': 1,
  },
  {
    'id': 18,
    'name': 'Old Skool',
    'brand': 'Vans',
    'price': 60.00,
    'category': 'Casual',
    'description': 'The classic sidestripe skate shoe.',
    'sizes': '7,8,9,10,11,12',
    'colors': 'Black,Checkerboard',
    'images': 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
    'is_featured': 0,
    'is_new_arrival': 0,
  },
  {
    'id': 19,
    'name': 'Puma Suede',
    'brand': 'Puma',
    'price': 70.00,
    'category': 'Sneakers',
    'description': 'The classic silhouette for street style.',
    'sizes': '8,9,10',
    'colors': 'Navy,Black,Red',
    'images': 'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=800&q=80',
    'is_featured': 0,
    'is_new_arrival': 0,
  },
  {
    'id': 20,
    'name': 'Dame 8',
    'brand': 'Adidas',
    'price': 120.00,
    'category': 'Sport',
    'description': 'Damian Lillards high-performance basketball shoe.',
    'sizes': '8,9,10,11',
    'colors': 'Black,Green,White',
    'images': 'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?auto=format&fit=crop&w=800&q=80',
    'is_featured': 0,
    'is_new_arrival': 0,
  },
  {
    'id': 21,
    'name': 'Nike Blazer Low',
    'brand': 'Nike',
    'price': 85.00,
    'category': 'Sneakers',
    'description': 'Classic style with a low-top silhouette.',
    'sizes': '7,8,9,10',
    'colors': 'White,Vintage',
    'images': 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=800&q=80',
    'is_featured': 0,
    'is_new_arrival': 0,
  },
  {
    'id': 22,
    'name': 'Gel-Kayano 29',
    'brand': 'ASICS',
    'price': 160.00,
    'category': 'Running',
    'description': 'Stability runner for overpronators.',
    'sizes': '8,9,10,11',
    'colors': 'Blue,Black',
    'images': 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80',
    'is_featured': 0,
    'is_new_arrival': 0,
  },
  {
    'id': 23,
    'name': 'Clyde All-Pro',
    'brand': 'Puma',
    'price': 130.00,
    'category': 'Sport',
    'description': 'The ultimate basketball shoe for on-court elite performance.',
    'sizes': '9,10,11',
    'colors': 'White,Black,Gold',
    'images': 'https://images.unsplash.com/photo-1512374382149-433a72b9a5a5?auto=format&fit=crop&w=800&q=80',
    'is_featured': 1,
    'is_new_arrival': 1,
  },
  {
    'id': 24,
    'name': 'NMD R1',
    'brand': 'Adidas',
    'price': 150.00,
    'category': 'Sneakers',
    'description': 'Modern look with energy-returning boost.',
    'sizes': '8,9,10,11',
    'colors': 'Black,White',
    'images': 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=800&q=80',
    'is_featured': 0,
    'is_new_arrival': 0,
  },
  {
    'id': 25,
    'name': 'Wallabee',
    'brand': 'Clarks',
    'price': 150.00,
    'category': 'Casual',
    'description': 'The iconic moccasin construction.',
    'sizes': '8,9,10',
    'colors': 'Beige,Black',
    'images': 'https://images.unsplash.com/photo-1531310197839-ccf54634509e?auto=format&fit=crop&w=800&q=80',
    'is_featured': 0,
    'is_new_arrival': 0,
  },
  {
    'id': 26,
    'name': 'Adizero Adios Pro 3',
    'brand': 'Adidas',
    'price': 250.00,
    'category': 'Running',
    'description': 'The ultimate long-distance racing shoe.',
    'sizes': '8,9,10',
    'colors': 'Yellow,Multi',
    'images': 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    'is_featured': 1,
    'is_new_arrival': 1,
  },
  {
    'id': 27,
    'name': 'Jordan 4 Retro',
    'brand': 'Nike',
    'price': 200.00,
    'category': 'Sneakers',
    'description': 'One of the most beloved Air Jordan models.',
    'sizes': '9,10,11,12',
    'colors': 'Grey,Black,Red',
    'images': 'https://images.unsplash.com/photo-1597043530274-0466e33ca270?auto=format&fit=crop&w=800&q=80',
    'is_featured': 0,
    'is_new_arrival': 1,
  },
  {
    'id': 28,
    'name': 'Stan Smith',
    'brand': 'Adidas',
    'price': 95.00,
    'category': 'Casual',
    'description': 'Timeless classic tennis shoe.',
    'sizes': '7,8,9,10',
    'colors': 'White,Green',
    'images': 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
    'is_featured': 0,
    'is_new_arrival': 0,
  },
  {
    'id': 29,
    'name': 'Hoka Clifton 9',
    'brand': 'Hoka',
    'price': 145.00,
    'category': 'Running',
    'description': 'Signature cushioning and smooth ride.',
    'sizes': '8,9,10,11',
    'colors': 'Blue,White',
    'images': 'https://images.unsplash.com/photo-1605348532760-6753d2c41329?auto=format&fit=crop&w=800&q=80',
    'is_featured': 0,
    'is_new_arrival': 0,
  },
  {
    'id': 30,
    'name': 'LeBron 20',
    'brand': 'Nike',
    'price': 200.00,
    'category': 'Sport',
    'description': 'LeBron Jamess latest performance basketball shoe.',
    'sizes': '9,10,11,12',
    'colors': 'Pink,Black,Multi',
    'images': 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&w=800&q=80',
    'is_featured': 1,
    'is_new_arrival': 0,
  },
];
